version: "3.9"
name: pevn-app
services:
  database:
    image: postgres:12-alpine
    container_name: database
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=prod-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    restart: always
    build: ./backend
    container_name: backend
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./backend:/opt/app/backend
      - ./backend/package.json:/opt/app/package.json
      - ./backend/package-lock.json:/opt/app/package-lock.json
      - notused:/opt/app/backend/node_modules
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=prod-db
      - DB_HOST=database
    command: npm run start:dev
  frontend:
    restart: always
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/opt/app/frontend
      - ./frontend/package.json:/opt/app/package.json
      - ./frontend/package-lock.json:/opt/app/package-lock.json
      - notused:/opt/app/frontend/node_modules
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - REST_API_URL=http://backend:3001
    command: npm run dev

volumes:
  notused:
